"""
Summarize stage implementation for the longtext pipeline.

This module provides the SummarizeStage class for generating summaries
of individual text parts using LLM-based analysis. Implements part-level
summarization with support for both General and Relationship modes.
"""

import asyncio
from datetime import datetime
from pathlib import Path
from typing import Any, List, Optional

from ..errors import LLMError, StageFailedError
from ..llm.factory import get_llm_client
from ..manifest import ManifestManager
from ..models import Manifest, Part, Summary
from ..utils.io import read_file, write_file
from ..utils.token_estimator import estimate_tokens


class SummarizeStage:
    """Generates LLM-based summaries for each part from the ingest stage.
    
    The summarize stage processes each part file independently, calling an LLM
    to generate a structured summary. It supports both General and Relationship
    modes (experimental) via different prompt templates. Implements Continue-with-
    Partial error handling to maximize throughput despite individual failures.
    """
    
    def __init__(self, manifest_manager: Optional[ManifestManager] = None):
        """Initialize the summarize stage.
        
        Args:
            manifest_manager: Optional existing manifest manager
        """
        self.manifest_manager = manifest_manager or ManifestManager()
    
    def _load_prompt_template(self, mode: str) -> str:
        """Load prompt template from file based on mode.
        
        Args:
            mode: Either 'general' or 'relationship'
            
        Returns:
            Prompt template string
            
        Raises:
            FileNotFoundError: If prompt template file not found
        """
        # Determine prompt file based on mode
        if mode == "relationship":
            prompt_file = "summary_relationship.txt"
        else:
            prompt_file = "summary_general.txt"
        
        # Build path to prompts directory
        prompts_dir = Path(__file__).parent.parent / "prompts"
        prompt_path = prompts_dir / prompt_file
        
        # Load prompt template
        try:
            return read_file(str(prompt_path))
        except FileNotFoundError:
            raise FileNotFoundError(
                f"Prompt template not found: {prompt_path}. "
                f"Ensure {prompt_file} exists in the prompts directory."
            )
    
    async def _generate_summary(
        self, 
        part: Part, 
        part_path: str,
        prompt_template: str, 
        client,
        model: str
    ) -> Summary:
        """Generate summary for a single part.
        
        Args:
            part: Part object to summarize
            part_path: Path to the part file
            prompt_template: Loaded prompt template
            client: LLM client instance
            model: Model name for metadata
            
        Returns:
            Summary object with generated content and metadata
            
        Raises:
            LLMError: If LLM call fails
        """
        # Build full prompt by appending part content
        full_prompt = prompt_template + part.content
        
        # Call LLM to generate summary (async)
        response = await client.acomplete(full_prompt)
        
        # Parse response into Summary object
        timestamp = datetime.now()
        summary = Summary(
            part_index=part.index,
            content=response,
            metadata={
                "generated_at": timestamp.isoformat(),
                "part_file": part_path,
                "model": model,
                "estimated_tokens": estimate_tokens(response)
            }
        )
        
        return summary
    
    def _save_summary(self, summary: Summary, parts_dir: Path) -> str:
        """Save summary to file and return path.
        
        Args:
            summary: Summary object to save
            parts_dir: Directory to save summary in
            
        Returns:
            Path to saved summary file
        """
        summary_filename = f"summary_{summary.part_index:02d}.md"
        summary_path = parts_dir / summary_filename
        
        # Format summary content with frontmatter
        timestamp = summary.metadata.get("generated_at", datetime.now().isoformat())
        part_file_rel = Path(summary.metadata.get("part_file", "unknown")).name
        model = summary.metadata.get("model", "unknown")
        
        summary_content = f"""# Summary for Part {summary.part_index:02d}

**Generated:** {timestamp}  
**Part File:** {part_file_rel}  
**Tokens:** {summary.metadata.get('estimated_tokens', 'N/A')}  
**Mode:** {summary.metadata.get('mode', 'general')}

{summary.content}

---

_Summary generated by {model} ({timestamp})_
"""
        
        write_file(summary_path, summary_content)
        return str(summary_path)
    
    async def run(
        self,
        parts: List[Part],
        config: dict[str, Any],
        manifest: Manifest,
        mode: str = "general",
    ) -> List[Summary]:
        """Async run the summarize stage on all parts.
        
        Args:
            parts: List of Part objects from ingest stage
            config: Configuration dictionary with LLM settings
            manifest: Manifest object to update
            mode: Analysis mode ('general' or 'relationship')
            
        Returns:
            List of Summary objects for successfully processed parts
            
        Raises:
            StageFailedError: If all parts fail (but may contain partial results)
        """
        # Validate mode parameter
        if mode not in ("general", "relationship"):
            raise ValueError(
                f"Invalid mode: '{mode}'. Must be 'general' or 'relationship'."
            )
        
        # Log experimental mode warning
        if mode == "relationship":
            print("[SummarizeStage] EXPERIMENTAL MODE: Relationship-focused analysis enabled")
        
        # Update manifest to indicate started summarize stage
        self.manifest_manager.update_stage(manifest, 'summarize', 'running')
        
        # Load prompt template
        prompt_template = self._load_prompt_template(mode)
        
        # Create LLM client using agent-specific model config for summarizer
        client = get_llm_client(config, agent_type='summarizer')
        model = getattr(client, "model", "unknown")
        
        # Determine output directory
        output_dir = Path(manifest.input_path).parent / ".longtext"
        output_dir.mkdir(exist_ok=True)
        
        # Get max workers from config
        max_workers = config.get('pipeline', {}).get('max_workers', 4)
        semaphore = asyncio.Semaphore(max_workers)
        
        # Track results and errors
        summaries: List[Summary] = []
        saved_summary_paths: List[str] = []
        errors: List[dict[str, Any]] = []
        
        # Define async worker function for processing parts
        async def process_part(part: Part):
            async with semaphore:  # Limit concurrent execution
                # Check if part should be skipped (e.g., tiny input marked in ingest)
                if part.metadata.get('skip_summary', False):
                    reason = part.metadata.get('reason', 'Unknown')
                    print(f"[SummarizeStage] Skipping part {part.index}: {reason}")
                    
                    # Create empty summary for skipped parts
                    summary = Summary(
                        part_index=part.index,
                        content="[Skipped - tiny input]",
                        metadata={
                            "skipped": True,
                            "skip_reason": reason,
                            "generated_at": datetime.now().isoformat()
                        }
                    )
                    return summary, "", None  # Success, summary, path, no error
                
                # Construct part file path
                part_filename = f"part_{part.index:02d}.txt"
                part_path = output_dir / part_filename
                
                try:
                    print(f"[SummarizeStage] Processing part {part.index}...")
                    
                    # Generate summary (async)
                    summary = await self._generate_summary(
                        part=part,
                        part_path=str(part_path),
                        prompt_template=prompt_template,
                        client=client,
                        model=model
                    )
                    
                    # Add mode to metadata
                    summary.metadata['mode'] = mode
                    
                    # Save summary to file
                    summary_path = self._save_summary(summary, output_dir)
                    
                    print(f"[SummarizeStage] Completed part {part.index}: {summary_path}")

                    return summary, summary_path, None  # Success
                    
                except LLMError as e:
                    # Handle LLM error for this part - continue with others
                    error_info = {
                        "index": part.index,
                        "file": str(part_path),
                        "error": str(e)
                    }
                    print(f"[SummarizeStage] Failed part {part.index}: {e}")
                    return None, "", error_info
                    
                except Exception as e:
                    # Handle unexpected errors - continue with others
                    error_info = {
                        "index": part.index,
                        "file": str(part_path),
                        "error": f"Unexpected error: {str(e)}"
                    }
                    print(f"[SummarizeStage] Unexpected error on part {part.index}: {e}")
                    return None, "", error_info
        
        # Schedule all parts for concurrent execution
        tasks = [process_part(part) for part in parts]
        results = await asyncio.gather(*tasks)

        # Process results maintaining order from original parts list
        for result in results:
            summary, summary_path, error = result
            if error:
                # Error occurred
                errors.append(error)
            else:
                # Success case, add to appropriate lists
                if summary:
                    summaries.append(summary)
                    saved_summary_paths.append(summary_path)
        
        # Calculate statistics
        total_parts = len(parts)
        successful = len([s for s in summaries if not s.metadata.get('skipped', False) and s.content != "[Skipped - tiny input]"])
        skipped = len([s for s in summaries if s.metadata.get('skipped', False)])
        failed = len(errors)
        
        # Prepare manifest statistics
        stats = {
            "summaries_completed": successful,
            "summaries_total": total_parts,
            "summaries_skipped": skipped,
            "errors": errors,
            "saved_summaries": saved_summary_paths
        }
        
        # Determine stage status
        if successful == 0 and failed == total_parts:
            # All parts failed
            stage_status = "failed"
            error_message = f"All {total_parts} parts failed to summarize"
            self.manifest_manager.update_stage(
                manifest, 
                'summarize', 
                stage_status, 
                error=error_message,
                stats=stats
            )
            raise StageFailedError(
                stage_name="summarize",
                errors=[Exception(e["error"]) for e in errors],
                partial_result=summaries
            )
        elif failed > 0:
            # Partial success
            stage_status = "successful"  # Stage succeeded overall with partials
            print(f"[SummarizeStage] Partial success: {successful}/{total_parts} successful, {failed} failed")
            self.manifest_manager.update_stage(
                manifest,
                'summarize',
                stage_status,
                stats=stats
            )
        else:
            # All succeeded
            stage_status = "successful"
            self.manifest_manager.update_stage(
                manifest,
                'summarize',
                stage_status,
                stats=stats
            )
        
        # Update manifest status
        manifest.status = 'summarizing'
        manifest.updated_at = datetime.now()
        self.manifest_manager.save_manifest(manifest)
        
        # Return successfully generated summaries
        return summaries
