"""Renderer module for pipeline result formatting.

This module provides formatting functions for all pipeline output types:
- Summary objects (part summaries)
- StageSummary objects (stage syntheses)
- FinalAnalysis objects (final comprehensive analysis)
- Manifest objects (pipeline state)

All renderings follow DATA_MODEL.md specifications and include comprehensive
metadata (timestamp, sources, token counts, stage status).
"""

from datetime import datetime
from typing import Any, Dict, List, Optional

from .models import FinalAnalysis, Manifest, StageInfo, StageSummary, Summary


# === Template strings ===

SUMMARY_TEMPLATE = """# Summary for Part {part_index:02d}

**Generated:** {timestamp}  
**Part File:** {part_file}  
**Tokens:** {token_count}  
**Model:** {model}

## Key Points
{key_points}

## Entities Identified  
{entities}

## Themes
{themes}

## Action Items {action_items_header}
{action_items}

## Additional Notes
{notes}

---

_Summary generated by {model} ({timestamp})_
"""

STAGE_TEMPLATE = """# Stage Summary {stage_index:02d}

**Generated:** {timestamp}  
**Combined From:** {combined_from}  
**Summary Count:** {summary_count}  
**Tokens:** {token_count}  
**Model:** {model}

## Executive Summary  
{executive_summary}

## Consolidated Key Points
{consolidated_points}

## Entity Synthesis
{entity_synthesis}

## Theme Evolution
{theme_evolution}

## Consistency Checks
{consistency_checks}

## Action Items Tracking
{action_items_tracking}

---

_Staged synthesized by {model} ({timestamp})_
"""

FINAL_TEMPLATE = """# Final Analysis for {input_filename}

**Generated:** {timestamp}
**Source File:** [{input_filename}]({input_path})
**Analysis Scope:** {parts_count} parts, {stages_count} stages analyzed
**Processing Time:** {processing_time}s
**Tokens Analyzed:** {tokens_analyzed}
**Models Used:** {models_used}

## Executive Summary
{executive_summary}

## Comprehensive Theme Analysis
{theme_analysis}

## Participant Analysis  
{participant_analysis}

## Timeline Reconstruction 
{timeline_reconstruction}

## Anomalies and Edge Cases
{anomalies}

## Implications and Recommendations  
{recommendations}

## Confidence Assessment
{confidence_assessment}

---

_Final analysis generated by {model} ({timestamp})_

**Confidence Level:** [ ] High [ ] Medium [ ] Low  
**Review Needed:** [ ] Yes [ ] No [ ] Critical Elements Only
"""

MANIFEST_STATUS_TEMPLATE = """Pipeline Status Report
======================

Session ID: {session_id}
Status: {overall_status}
Input File: {input_path}

Created: {created_at}
Last Updated: {updated_at}

Processing Summary:
- Total Parts: {total_parts}
- Total Stages: {total_stages}  
- Estimated Tokens: {estimated_tokens}

Stage Status:
{stage_status}

{error_summary}
"""


# === Helper functions ===


def _get_timestamp() -> str:
    """Get current timestamp in ISO 8601 format."""
    return datetime.now().isoformat(timespec="seconds")


def _format_list(items: List[str], prefix: str = "- ") -> str:
    """Format a list of strings as a bullet list."""
    if not items:
        return "(none)"
    return "\n".join(f"{prefix}{item}" for item in items)


def _format_dict(data: Dict, indent: int = 0) -> str:
    """Format a dictionary as indented key-value pairs."""
    if not data:
        return "(none)"

    indent_str = "  " * indent
    lines = []
    for key, value in data.items():
        if isinstance(value, dict):
            lines.append(f"{indent_str}{key}:")
            lines.append(_format_dict(value, indent + 1))
        else:
            lines.append(f"{indent_str}{key}: {value}")
    return "\n".join(lines)


def _safe_get(data: Dict, *keys, default: str = "(not available)") -> str:
    """Safely get nested dictionary values with default fallback."""
    result: Any = data
    for key in keys:
        if isinstance(result, dict):
            result = result.get(key, default)
        else:
            return default
    return str(result) if result is not None else default


def _format_stage_info(info: Optional[StageInfo]) -> str:
    """Format a StageInfo object as a readable string."""
    if info is None:
        return "  - Status: (not tracked)"

    lines = [
        f"  - Status: {info.status}",
    ]

    if info.input_file:
        lines.append(f"  - Input: {info.input_file}")
    if info.output_file:
        lines.append(f"  - Output: {info.output_file}")
    if info.timestamp:
        lines.append(f"  - Timestamp: {info.timestamp.isoformat(timespec='seconds')}")
    if info.error:
        lines.append(f"  - Error: {info.error}")

    return "\n".join(lines)


# === Main renderer functions ===


def render_summary(summary: Summary, model: str = "unknown") -> str:
    """Format a Summary object as markdown.

    Args:
        summary: Summary object to render
        model: LLM model name used for generation

    Returns:
        Formatted markdown string following DATA_MODEL.md Summary format
    """
    # Extract parts from content or use defaults
    content = summary.content.strip()

    # Try to parse structured sections (Key Points, Entities, etc.)
    sections = {
        "key_points": "(none)",
        "entities": "(none)",
        "themes": "(none)",
        "action_items": "(none)",
        "notes": "(none)",
    }

    # Simple section extraction from markdown content
    current_section = "notes"
    current_lines: List[str] = []

    for line in content.split("\n"):
        line_stripped = line.strip()

        if line_stripped.startswith("## "):
            section_name = line_stripped[3:].lower()
            # Save previous section
            if current_lines and current_section in sections:
                sections[current_section] = "\n".join(current_lines)
            # Start new section
            current_section = section_name.replace(" ", "_")
            current_lines = []
        elif line_stripped and not line_stripped.startswith("#"):
            current_lines.append(line)

    # Save last section
    if current_lines and current_section in sections:
        sections[current_section] = "\n".join(current_lines)

    # Build formatted output
    return SUMMARY_TEMPLATE.format(
        part_index=summary.part_index,
        timestamp=_get_timestamp(),
        part_file=f"part_{summary.part_index:02d}.txt",
        token_count=summary.metadata.get("token_count", "(estimating)"),
        model=model,
        key_points=sections["key_points"],
        entities=sections["entities"],
        themes=sections["themes"],
        action_items_header="(if applicable)",
        action_items=sections["action_items"],
        notes=sections["notes"],
    )


def render_stage(stage: StageSummary, model: str = "unknown") -> str:
    """Format a StageSummary object as markdown.

    Args:
        stage: StageSummary object to render
        model: LLM model name used for generation

    Returns:
        Formatted markdown string following DATA_MODEL.md Stage format
    """
    # Extract synthesis content
    synthesis = stage.synthesis.strip()

    # Try to parse structured sections
    sections: Dict[str, str] = {
        "executive_summary": "(none)",
        "consolidated_points": "(none)",
        "entity_synthesis": "(none)",
        "theme_evolution": "(none)",
        "consistency_checks": "(none)",
        "action_items_tracking": "(none)",
    }

    current_section = "executive_summary"
    current_lines: List[str] = []

    for line in synthesis.split("\n"):
        line_stripped = line.strip()

        if line_stripped.startswith("## "):
            section_name = line_stripped[3:].lower()
            if current_lines and current_section in sections:
                sections[current_section] = "\n".join(current_lines)
            current_section = section_name.replace(" ", "_")
            current_lines = []
        elif line_stripped and not line_stripped.startswith("#"):
            current_lines.append(line)

    if current_lines and current_section in sections:
        sections[current_section] = "\n".join(current_lines)

    # Build summary references
    summary_files = []
    for s in stage.summaries:
        summary_files.append(
            f"[summary_{s.part_index:02d}.md](./summary_{s.part_index:02d}.md)"
        )

    # Calculate token count
    token_count = stage.metadata.get("token_count", "(estimating)")

    return STAGE_TEMPLATE.format(
        stage_index=stage.stage_index,
        timestamp=_get_timestamp(),
        combined_from=", ".join(summary_files) if summary_files else "(none)",
        summary_count=len(stage.summaries),
        token_count=token_count,
        model=model,
        executive_summary=sections["executive_summary"],
        consolidated_points=sections["consolidated_points"],
        entity_synthesis=sections["entity_synthesis"],
        theme_evolution=sections["theme_evolution"],
        consistency_checks=sections["consistency_checks"],
        action_items_tracking=sections["action_items_tracking"],
    )


def render_final(
    final: FinalAnalysis, input_path: str = "(unknown)", model: str = "unknown"
) -> str:
    """Format a FinalAnalysis object as markdown.

    Args:
        final: FinalAnalysis object to render
        input_path: Path to original input file
        model: LLM model name used for generation

    Returns:
        Formatted markdown string following DATA_MODEL.md Final Analysis format
    """
    # Extract final result content
    final_result = final.final_result.strip()

    # Try to parse structured sections
    sections: Dict[str, str] = {
        "executive_summary": "(none)",
        "theme_analysis": "(none)",
        "participant_analysis": "(none)",
        "timeline_reconstruction": "(none)",
        "anomalies": "(none)",
        "recommendations": "(none)",
        "confidence_assessment": "(none)",
    }

    current_section = "executive_summary"
    current_lines: List[str] = []

    for line in final_result.split("\n"):
        line_stripped = line.strip()

        if line_stripped.startswith("## "):
            section_name = line_stripped[3:].lower()
            if current_lines and current_section in sections:
                sections[current_section] = "\n".join(current_lines)
            current_section = section_name.replace(" ", "_")
            current_lines = []
        elif line_stripped and not line_stripped.startswith("#"):
            current_lines.append(line)

    if current_lines and current_section in sections:
        sections[current_section] = "\n".join(current_lines)

    # Calculate derived values
    # Handle both forward and backward slashes for cross-platform compatibility
    input_filename = (
        input_path.split("/")[-1].split("\\")[-1]
        if "/" in input_path or "\\" in input_path
        else input_path
    )

    parts_count = 0
    for stage in final.stages:
        parts_count += len(stage.summaries)

    stages_count = len(final.stages)

    # Calculate tokens from all stages
    total_tokens = 0
    for stage in final.stages:
        for summary in stage.summaries:
            total_tokens += summary.metadata.get("token_count", 0)
        total_tokens += stage.metadata.get("token_count", 0)
    total_tokens += final.metadata.get("token_count", 0)

    # Get models used from metadata
    models_used = (
        final.metadata.get("models_used", [model])
        if isinstance(final.metadata.get("models_used"), list)
        else model
    )
    if isinstance(models_used, list):
        models_used = ", ".join(str(m) for m in models_used)

    # Calculate processing time
    created_at = final.metadata.get("created_at")
    completed_at = final.metadata.get("completed_at")

    processing_time = "(unknown)"
    if created_at and completed_at:
        try:
            if isinstance(created_at, str):
                created_at = datetime.fromisoformat(created_at.replace("Z", "+00:00"))
            if isinstance(completed_at, str):
                completed_at = datetime.fromisoformat(
                    completed_at.replace("Z", "+00:00")
                )

            delta = completed_at - created_at
            processing_time = str(int(delta.total_seconds()))
        except (ValueError, TypeError):
            processing_time = "(calculation failed)"

    return FINAL_TEMPLATE.format(
        input_filename=input_filename,
        timestamp=_get_timestamp(),
        input_path=input_path,
        parts_count=parts_count,
        stages_count=stages_count,
        processing_time=processing_time,
        tokens_analyzed=total_tokens,
        models_used=models_used,
        executive_summary=sections["executive_summary"],
        theme_analysis=sections["theme_analysis"],
        participant_analysis=sections["participant_analysis"],
        timeline_reconstruction=sections["timeline_reconstruction"],
        anomalies=sections["anomalies"],
        recommendations=sections["recommendations"],
        confidence_assessment=sections["confidence_assessment"],
        model=model,
    )


def render_manifest_status(manifest: Manifest) -> str:
    """Format a Manifest object as a status report.

    Args:
        manifest: Manifest object to render

    Returns:
        Formatted status report string
    """
    # Build stage status section
    stage_lines = []
    stage_order = ["ingest", "summarize", "stage", "final", "audit"]

    for stage_name in stage_order:
        stage_info = manifest.stages.get(stage_name)
        status_str = _format_stage_info(stage_info)
        stage_lines.append(f"{stage_name}:")
        stage_lines.append(status_str)

    stage_status = "\n".join(stage_lines)

    # Build error summary
    error_lines = []
    for stage_name, stage_info in manifest.stages.items():
        if stage_info and stage_info.error:
            error_lines.append(f"ERROR in {stage_name} stage:")
            error_lines.append(f"  {stage_info.error}")

    error_summary = "\n".join(error_lines) if error_lines else "(no errors)"

    # Format timestamps
    created_at = (
        manifest.created_at.isoformat(timespec="seconds")
        if manifest.created_at
        else "(unknown)"
    )
    updated_at = (
        manifest.updated_at.isoformat(timespec="seconds")
        if manifest.updated_at
        else "(unknown)"
    )

    # Format token counts
    total_parts = manifest.total_parts if manifest.total_parts else "(not tracked)"
    total_stages = manifest.total_stages if manifest.total_stages else "(not tracked)"
    estimated_tokens = (
        manifest.estimated_tokens if manifest.estimated_tokens else "(not tracked)"
    )

    return MANIFEST_STATUS_TEMPLATE.format(
        session_id=manifest.session_id,
        overall_status=manifest.status,
        input_path=manifest.input_path,
        created_at=created_at,
        updated_at=updated_at,
        total_parts=total_parts,
        total_stages=total_stages,
        estimated_tokens=estimated_tokens,
        stage_status=stage_status,
        error_summary=error_summary,
    )


# === CLI helper functions ===


def format_status(manifest: Manifest, show_details: bool = False) -> str:
    """Format manifest for CLI status command output.

    Args:
        manifest: Manifest object
        show_details: Whether to include detailed stage information

    Returns:
        Formatted status string for CLI display with comprehensive pipeline state
    """
    lines = []

    # === Section 1: Session Information ===
    lines.append("=" * 60)
    lines.append("PIPELINE STATUS REPORT")
    lines.append("=" * 60)
    lines.append("")
    lines.append("SESSION INFORMATION")
    lines.append("-" * 60)
    lines.append(f"Session ID:    {manifest.session_id}")

    # Status with visual indicator
    status_icon = {
        "not_started": "○",
        "running": "◐",
        "successful": "✓",
        "failed": "✗",
        "partial_success": "⚠",
        "completed": "✓",
        "completed_with_issues": "⚠",
    }.get(manifest.status, "?")
    lines.append(f"Overall Status: [{status_icon}] {manifest.status}")

    created_at = (
        manifest.created_at.isoformat(timespec="seconds")
        if manifest.created_at
        else "N/A"
    )
    updated_at = (
        manifest.updated_at.isoformat(timespec="seconds")
        if manifest.updated_at
        else "N/A"
    )
    lines.append(f"Created:       {created_at}")
    lines.append(f"Last Updated:  {updated_at}")

    # === Section 2: Input Information ===
    lines.append("")
    lines.append("INPUT INFORMATION")
    lines.append("-" * 60)
    lines.append(f"File Path: {manifest.input_path}")
    lines.append(f"File Hash: {manifest.input_hash[:16]}...{manifest.input_hash[-16:]}")

    # === Section 3: Stage Progress Table ===
    lines.append("")
    lines.append("STAGE PROGRESS")
    lines.append("-" * 60)

    # Table header
    lines.append(f"{'Stage':<12} {'Status':<15} {'Timestamp':<20} {'Output File'}")
    lines.append("-" * 60)

    stage_order = ["ingest", "summarize", "stage", "final", "audit"]
    for stage_name in stage_order:
        stage_info = manifest.stages.get(stage_name)

        if stage_info:
            status = stage_info.status
            # Visual status indicator
            status_display = {
                "not_started": "○ Not Started",
                "running": "◐ Running",
                "successful": "✓ Success",
                "failed": "✗ Failed",
                "skipped": "- Skipped",
            }.get(status, f"? {status}")

            timestamp = "—"
            if stage_info.timestamp:
                timestamp = stage_info.timestamp.strftime("%Y-%m-%d %H:%M:%S")

            output_file = "—"
            if stage_info.output_file:
                # Truncate long paths for display
                output_file = stage_info.output_file
                if len(output_file) > 40:
                    output_file = "..." + output_file[-37:]

            lines.append(
                f"{stage_name:<12} {status_display:<15} {timestamp:<20} {output_file}"
            )

    # === Section 4: Statistics Summary ===
    lines.append("")
    lines.append("STATISTICS")
    lines.append("-" * 60)

    total_parts = manifest.total_parts if manifest.total_parts is not None else "N/A"
    total_stages = manifest.total_stages if manifest.total_stages is not None else "N/A"
    estimated_tokens = (
        manifest.estimated_tokens if manifest.estimated_tokens is not None else "N/A"
    )

    lines.append(f"Total Parts:        {total_parts}")
    lines.append(f"Total Stages:       {total_stages}")
    lines.append(f"Estimated Tokens:   {estimated_tokens}")

    # Calculate time elapsed since creation
    if manifest.created_at:
        now = datetime.now()
        created = manifest.created_at
        if isinstance(created, str):
            created = datetime.fromisoformat(created)
        elapsed = now - created
        days = elapsed.days
        hours, remainder = divmod(int(elapsed.total_seconds()), 3600)
        minutes, seconds = divmod(remainder, 60)

        if days > 0:
            elapsed_str = f"{days}d {hours}h {minutes}m {seconds}s"
        elif hours > 0:
            elapsed_str = f"{hours}h {minutes}m {seconds}s"
        elif minutes > 0:
            elapsed_str = f"{minutes}m {seconds}s"
        else:
            elapsed_str = f"{seconds}s"
        lines.append(f"Time Elapsed:       {elapsed_str}")

    # === Section 5: Error Summary ===
    lines.append("")
    lines.append("ERROR SUMMARY")
    lines.append("-" * 60)

    failed_stages = [
        (name, info)
        for name, info in manifest.stages.items()
        if info and info.status == "failed"
    ]
    stage_with_errors = [
        (name, info) for name, info in manifest.stages.items() if info and info.error
    ]

    if failed_stages or stage_with_errors:
        for stage_name, info in failed_stages:
            lines.append(f"✗ FAILED: {stage_name.upper()}")
            lines.append(f"  Status: {info.status}")
            if info.error:
                lines.append(f"  Error: {info.error}")
            if info.timestamp:
                lines.append(f"  Time: {info.timestamp.strftime('%Y-%m-%d %H:%M:%S')}")
            lines.append("")

        # Show stages with errors but not necessarily failed
        for stage_name, info in stage_with_errors:
            if info.status != "failed" and info.error:
                lines.append(f"⚠ WARNING: {stage_name.upper()}")
                lines.append(f"  Status: {info.status}")
                lines.append(f"  Error: {info.error}")
                lines.append("")
    else:
        lines.append("✓ No errors detected")

    # === Section 6: Next Action Suggestion ===
    lines.append("")
    lines.append("NEXT ACTION")
    lines.append("-" * 60)

    # Determine next action based on current state
    next_action = _determine_next_action(manifest)
    lines.append(next_action)

    lines.append("")
    lines.append("=" * 60)

    return "\n".join(lines)


def _determine_next_action(manifest: Manifest) -> str:
    """Determine the next suggested action based on pipeline state.

    Args:
        manifest: Manifest object to analyze

    Returns:
        Suggested next action string
    """
    # Import here to avoid potential circular dependency
    from .models import StageInfo

    # Check if already completed
    if manifest.status in ["completed", "successful"]:
        return (
            "✓ Pipeline completed successfully. Review output in final analysis file."
        )

    # Check for failures
    failed_stages = [
        name
        for name, info in manifest.stages.items()
        if info and info.status == "failed"
    ]

    if failed_stages:
        failed_stage = failed_stages[0]
        if failed_stage == "ingest":
            return "✗ Ingest stage failed. Check input file and configuration. Retry with: longtext run <input-file>"
        elif failed_stage == "summarize":
            return "✗ Summarize stage failed. Consider retrying or check LLM configuration. Resume with: --resume"
        elif failed_stage == "stage":
            return "✗ Stage synthesis failed. Check summary files and retry. Resume with: --resume"
        elif failed_stage == "final":
            return "✗ Final analysis failed. Stage syntheses may be incomplete. Resume with: --resume"
        else:
            return f"✗ {failed_stage} stage failed. Review error details above. Resume with: --resume"

    # Check overall status for partial success
    if manifest.status == "partial_success":
        return "⚠ Pipeline completed with partial success. Review completed stages and errors. Continue with: --resume"

    if manifest.status == "completed_with_issues":
        return "⚠ Pipeline completed with warnings. Review the final output and warning details above."

    # Check which stage we're at
    if (
        manifest.stages.get(
            "ingest", StageInfo(name="ingest", status="not_started")
        ).status
        == "not_started"
    ):
        return "▶ Start pipeline with: longtext run <input-file> --config <config.yaml>"

    if (
        manifest.stages.get(
            "summarize", StageInfo(name="summarize", status="not_started")
        ).status
        == "running"
    ):
        return "◐ Summarization in progress. Wait for completion or check logs for details."

    if (
        manifest.stages.get(
            "summarize", StageInfo(name="summarize", status="not_started")
        ).status
        == "not_started"
    ):
        return "▶ Continue with: longtext run <input-file> --resume"

    if (
        manifest.stages.get(
            "stage", StageInfo(name="stage", status="not_started")
        ).status
        == "running"
    ):
        return "◐ Stage synthesis in progress. Wait for completion or check logs for details."

    if (
        manifest.stages.get(
            "stage", StageInfo(name="stage", status="not_started")
        ).status
        == "not_started"
    ):
        return "▶ Continue with: --resume to proceed with stage synthesis"

    if (
        manifest.stages.get(
            "final", StageInfo(name="final", status="not_started")
        ).status
        == "running"
    ):
        return "◐ Final analysis in progress. Wait for completion or check logs for details."

    if (
        manifest.stages.get(
            "final", StageInfo(name="final", status="not_started")
        ).status
        == "not_started"
    ):
        return "▶ Continue with: --resume to proceed with final analysis"

    if (
        manifest.stages.get("audit", StageInfo(name="audit", status="skipped")).status
        == "skipped"
    ):
        return "✓ Pipeline complete. Optional: Run audit stage with: --audit"

    return "? Pipeline state unclear. Review manifest or start fresh with: longtext run <input-file>"


def format_output_type(output_type: str, content: str, **kwargs) -> str:
    """Generic output formatter dispatcher.

    Args:
        output_type: Type of output ('summary', 'stage', 'final', 'manifest')
        content: Content to format (can be object or plain text)
        **kwargs: Additional arguments for formatting

    Returns:
        Formatted output string
    """
    if output_type == "summary":
        if isinstance(content, Summary):
            return render_summary(content, **kwargs)
        return content

    elif output_type == "stage":
        if isinstance(content, StageSummary):
            return render_stage(content, **kwargs)
        return content

    elif output_type == "final":
        if isinstance(content, FinalAnalysis):
            return render_final(content, **kwargs)
        return content

    elif output_type == "manifest":
        if isinstance(content, Manifest):
            return render_manifest_status(content)
        return content

    elif output_type == "status":
        if isinstance(content, Manifest):
            return format_status(content, kwargs.get("show_details", False))
        return content

    else:
        return f"Unknown output type: {output_type}\n\n{content}"
